/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ems;

/**
 *
 * @author cristophechen
 */
public class addEmployee extends javax.swing.JFrame {
    
    HashTable ht;
    int number;

    /**
     * Creates new form addEmployee
     */
    public addEmployee() {
        initComponents();
        executionMessage.setText("");
    }
    
    public addEmployee(HashTable ht, int empNum) {
        initComponents();
        this.ht = ht;
        number = empNum;
        numberText.setText("Employee #" + number);
        executionMessage.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employeeType = new javax.swing.ButtonGroup();
        numberText = new javax.swing.JLabel();
        FTEButton = new javax.swing.JRadioButton();
        PTEButton = new javax.swing.JRadioButton();
        firstNameBox = new javax.swing.JTextField();
        lastNameBox = new javax.swing.JTextField();
        locationBox = new javax.swing.JTextField();
        deductionBox = new javax.swing.JTextField();
        salaryBox = new javax.swing.JTextField();
        weeklyBox = new javax.swing.JTextField();
        yearlyBox = new javax.swing.JTextField();
        addButton2 = new javax.swing.JButton();
        genderBox = new javax.swing.JComboBox<>();
        executionMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        numberText.setFont(new java.awt.Font("American Typewriter", 0, 18)); // NOI18N
        numberText.setText("Employee #");
        numberText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        employeeType.add(FTEButton);
        FTEButton.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        FTEButton.setText("Full-Time");
        FTEButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTEButtonActionPerformed(evt);
            }
        });

        employeeType.add(PTEButton);
        PTEButton.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        PTEButton.setText("Part-Time");
        PTEButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PTEButtonActionPerformed(evt);
            }
        });

        firstNameBox.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        firstNameBox.setText("First Name");
        firstNameBox.setActionCommand("<Not Set>");
        firstNameBox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        firstNameBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstNameBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstNameBoxFocusLost(evt);
            }
        });

        lastNameBox.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        lastNameBox.setText("Last Name");
        lastNameBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNameBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastNameBoxFocusLost(evt);
            }
        });

        locationBox.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        locationBox.setText("Work Location");
        locationBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                locationBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                locationBoxFocusLost(evt);
            }
        });

        deductionBox.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        deductionBox.setText("Deduction %");
        deductionBox.setActionCommand("<Not Set>");
        deductionBox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        deductionBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                deductionBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                deductionBoxFocusLost(evt);
            }
        });

        salaryBox.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        salaryBox.setText("Hourly Wage");
        salaryBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                salaryBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                salaryBoxFocusLost(evt);
            }
        });

        weeklyBox.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        weeklyBox.setText("Weekly Hours");
        weeklyBox.setActionCommand("<Not Set>");
        weeklyBox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        weeklyBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                weeklyBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                weeklyBoxFocusLost(evt);
            }
        });

        yearlyBox.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        yearlyBox.setText("Yearly Weeks");
        yearlyBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                yearlyBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                yearlyBoxFocusLost(evt);
            }
        });

        addButton2.setBackground(new java.awt.Color(102, 255, 51));
        addButton2.setFont(new java.awt.Font("American Typewriter", 0, 28)); // NOI18N
        addButton2.setForeground(new java.awt.Color(255, 255, 255));
        addButton2.setText("Add");
        addButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        addButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton2ActionPerformed(evt);
            }
        });

        genderBox.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        genderBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        genderBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                genderBoxFocusGained(evt);
            }
        });

        executionMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FTEButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PTEButton)
                            .addComponent(addButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(executionMessage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstNameBox)
                            .addComponent(deductionBox, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(weeklyBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(genderBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(locationBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salaryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearlyBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(numberText, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(numberText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FTEButton)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(locationBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(PTEButton)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deductionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salaryBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(weeklyBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearlyBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(executionMessage)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FTEButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTEButtonActionPerformed
        // TODO add your handling code here:
        weeklyBox.setVisible(false);
        yearlyBox.setVisible(false);
        if(salaryBox.getText().equals("Hourly Wage"))salaryBox.setText("Yearly Salary");
    }//GEN-LAST:event_FTEButtonActionPerformed

    private void addButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton2ActionPerformed
        // TODO add your handling code here:
        try{
            String firstName = firstNameBox.getText();
            String lastName = lastNameBox.getText();
            String gender = genderBox.getSelectedItem().toString();
            String location = locationBox.getText();
            double deduction = Double.parseDouble(deductionBox.getText());
            
            if(FTEButton.isSelected()){
                int salary = Integer.parseInt(salaryBox.getText());
                ht.addEmployee(new FTE(number, firstName, lastName, gender, location, deduction, salary));
                executionMessage.setText("Added FTE!");
            }
            else if(PTEButton.isSelected()){
                int wage = Integer.parseInt(salaryBox.getText());
                double weekly = Double.parseDouble(weeklyBox.getText());
                double yearly = Double.parseDouble(yearlyBox.getText());
                ht.addEmployee(new PTE(number, firstName, lastName, gender, location, deduction, wage, weekly, yearly));
                executionMessage.setText("Added PTE!");
            }
            else executionMessage.setText("Incomplete.");
        }
        catch(Exception e){
            executionMessage.setText("Invalid input.");
        }
    }//GEN-LAST:event_addButton2ActionPerformed

    private void genderBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_genderBoxFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_genderBoxFocusGained

    private void yearlyBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yearlyBoxFocusLost
        // TODO add your handling code here:
        if(yearlyBox.getText().equals(""))yearlyBox.setText("Yearly Weeks");
    }//GEN-LAST:event_yearlyBoxFocusLost

    private void weeklyBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_weeklyBoxFocusLost
        // TODO add your handling code here:
        if(weeklyBox.getText().equals(""))weeklyBox.setText("Weekly Hours");
    }//GEN-LAST:event_weeklyBoxFocusLost

    private void salaryBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salaryBoxFocusLost
        // TODO add your handling code here:
        if(salaryBox.getText().equals("")){
            if(FTEButton.isSelected())salaryBox.setText("Yearly Salary");
            else if(PTEButton.isSelected())salaryBox.setText("Hourly Wage");
            else salaryBox.setText("Hourly Wage");
        }
    }//GEN-LAST:event_salaryBoxFocusLost

    private void deductionBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deductionBoxFocusLost
        // TODO add your handling code here:
        if(deductionBox.getText().equals(""))deductionBox.setText("Deduction %");
    }//GEN-LAST:event_deductionBoxFocusLost

    private void locationBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_locationBoxFocusLost
        // TODO add your handling code here:
        if(locationBox.getText().equals(""))locationBox.setText("Work Location");
    }//GEN-LAST:event_locationBoxFocusLost

    private void lastNameBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameBoxFocusLost
        // TODO add your handling code here:
        if(lastNameBox.getText().equals(""))lastNameBox.setText("Last Name");
    }//GEN-LAST:event_lastNameBoxFocusLost

    private void yearlyBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yearlyBoxFocusGained
        // TODO add your handling code here:
        if(yearlyBox.getText().equals("Yearly Weeks"))yearlyBox.setText("");
    }//GEN-LAST:event_yearlyBoxFocusGained

    private void weeklyBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_weeklyBoxFocusGained
        // TODO add your handling code here:
        if(weeklyBox.getText().equals("Weekly Hours"))weeklyBox.setText("");
    }//GEN-LAST:event_weeklyBoxFocusGained

    private void salaryBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salaryBoxFocusGained
        // TODO add your handling code here:
        if(salaryBox.getText().equals("Hourly Wage") || salaryBox.getText().equals("Yearly Salary"))salaryBox.setText("");
    }//GEN-LAST:event_salaryBoxFocusGained

    private void deductionBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deductionBoxFocusGained
        // TODO add your handling code here:
        if(deductionBox.getText().equals("Deduction %"))deductionBox.setText("");
    }//GEN-LAST:event_deductionBoxFocusGained

    private void locationBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_locationBoxFocusGained
        // TODO add your handling code here:
        if(locationBox.getText().equals("Work Location"))locationBox.setText("");
    }//GEN-LAST:event_locationBoxFocusGained

    private void lastNameBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameBoxFocusGained
        // TODO add your handling code here:
        if(lastNameBox.getText().equals("Last Name"))lastNameBox.setText("");
    }//GEN-LAST:event_lastNameBoxFocusGained

    private void firstNameBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameBoxFocusLost
        // TODO add your handling code here:
        if(firstNameBox.getText().equals(""))firstNameBox.setText("First Name");
    }//GEN-LAST:event_firstNameBoxFocusLost

    private void firstNameBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameBoxFocusGained
        // TODO add your handling code here:
        if(firstNameBox.getText().equals("First Name"))firstNameBox.setText("");
    }//GEN-LAST:event_firstNameBoxFocusGained

    private void PTEButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PTEButtonActionPerformed
        // TODO add your handling code here:
        weeklyBox.setVisible(true);
        yearlyBox.setVisible(true);
        if(salaryBox.getText().equals("Yearly Salary"))salaryBox.setText("Hourly Wage");
    }//GEN-LAST:event_PTEButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton FTEButton;
    private javax.swing.JRadioButton PTEButton;
    private javax.swing.JButton addButton2;
    private javax.swing.JTextField deductionBox;
    private javax.swing.ButtonGroup employeeType;
    private javax.swing.JLabel executionMessage;
    private javax.swing.JTextField firstNameBox;
    private javax.swing.JComboBox<String> genderBox;
    private javax.swing.JTextField lastNameBox;
    private javax.swing.JTextField locationBox;
    private javax.swing.JLabel numberText;
    private javax.swing.JTextField salaryBox;
    private javax.swing.JTextField weeklyBox;
    private javax.swing.JTextField yearlyBox;
    // End of variables declaration//GEN-END:variables
}
