/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ems;

/**
 *
 * @author cristophechen
 */
public class changeEmployeeNumber extends javax.swing.JFrame {

    HashTable ht;
    
    /**
     * Creates new form changeEmployeeNumber
     */
    public changeEmployeeNumber() {
        initComponents();
    }
    
    public changeEmployeeNumber(HashTable ht){
        initComponents();
        this.ht = ht;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        oldNumBox = new javax.swing.JTextField();
        newNumBox = new javax.swing.JTextField();
        renumberButton1 = new javax.swing.JButton();
        renameOutcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("American Typewriter", 0, 16)); // NOI18N
        jLabel1.setText("Old Employee Number");

        jLabel2.setFont(new java.awt.Font("American Typewriter", 0, 16)); // NOI18N
        jLabel2.setText("New Employee Number");

        oldNumBox.setFont(new java.awt.Font("American Typewriter", 0, 15)); // NOI18N

        newNumBox.setFont(new java.awt.Font("American Typewriter", 0, 15)); // NOI18N

        renumberButton1.setBackground(new java.awt.Color(0, 0, 0));
        renumberButton1.setFont(new java.awt.Font("American Typewriter", 0, 22)); // NOI18N
        renumberButton1.setForeground(new java.awt.Color(255, 255, 255));
        renumberButton1.setText("Renumber");
        renumberButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        renumberButton1.setPreferredSize(new java.awt.Dimension(76, 37));
        renumberButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renumberButton1ActionPerformed(evt);
            }
        });

        renameOutcome.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        renameOutcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(oldNumBox, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(newNumBox, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(renumberButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(renameOutcome, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(oldNumBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(newNumBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(renameOutcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(renumberButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void renumberButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renumberButton1ActionPerformed
        // TODO add your handling code here:
        
        int oldEmpNum = Integer.parseInt(oldNumBox.getText());
        int newEmpNum = Integer.parseInt(newNumBox.getText());
        int index;

        index = ht.findIndex(newEmpNum);

        for(int i = 0; i < ht.employees[index].size(); ++i){
            if(ht.employees[index].get(i).empNum == newEmpNum){
                renameOutcome.setText("New number is already in use.");
                return;
            }
        }

        String firstName, lastName, gender, location;
        double deduction, salary, wage, weekly, yearly;

        index = ht.findIndex(oldEmpNum);
        
        if(ht.findEmployee(oldEmpNum) == -1){
            renameOutcome.setText("Old number does not exist.");
            return;
        }

        for(int i = 0; i < ht.employees[index].size(); ++i){
            if(ht.employees[index].get(i).empNum == oldEmpNum){
                firstName = ht.employees[index].get(i).firstName;
                lastName = ht.employees[index].get(i).lastName;
                gender = ht.employees[index].get(i).gender;
                location = ht.employees[index].get(i).workLoc;
                deduction = ht.employees[index].get(i).deductRate;

                if(ht.employees[index].get(i) instanceof FTE FTEemployee){
                    salary = FTEemployee.yearlySalary;

                    FTE newFTE = new FTE(newEmpNum, firstName, lastName, gender, location, deduction, salary);
                    ht.addEmployee(newFTE);
                }

                else if(ht.employees[index].get(i) instanceof PTE PTEemployee){
                    wage = PTEemployee.hourlyWage;
                    weekly = PTEemployee.weeklyHours;
                    yearly = PTEemployee.yearlyWeeks;

                    PTE newPTE = new PTE(newEmpNum, firstName, lastName, gender, location, deduction, wage, weekly, yearly);
                    ht.addEmployee(newPTE);
                }

            }
        }
        ht.removeEmployee(oldEmpNum);
        renameOutcome.setText("Sucessfully renumbered!");

    }//GEN-LAST:event_renumberButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changeEmployeeNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changeEmployeeNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changeEmployeeNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changeEmployeeNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changeEmployeeNumber().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField newNumBox;
    private javax.swing.JTextField oldNumBox;
    private javax.swing.JLabel renameOutcome;
    private javax.swing.JButton renumberButton1;
    // End of variables declaration//GEN-END:variables
}
